apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: ticketing
  labels:
    app.kubernetes.io/name: orders
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: orders
  ports:
    - name: http
      port: 5004
      targetPort: 5004
