apiVersion: v1
kind: Service
metadata:
  name: fakepaymentgateway
  namespace: ticketing
  labels:
    app.kubernetes.io/name: fakepaymentgateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fakepaymentgateway
  ports:
    - name: http
      port: 5006
      targetPort: 5006
