<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\aspire\ServiceDefaults\TicketingPlatform.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\..\building-blocks\observability\TicketingPlatform.Observability.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
